site_name: Lava Jato
repo_url: https://github.com/UnBArqDsw2021-2/2021.2_G2_lava-jato

theme:
  name: material
  features: navigation.tabs

nav:
  - Home: "index.md"
  - Heatmap: "heatmap.md"
  - TAP: "tap.md"
